[package]
name = "yastl"
version = "0.1.0"
authors = ["Justus K <justus.k@protonmail.com>"]
edition = "2018"

[dependencies]
scopeguard = "1.1"
flume = { version = "0.10", default-features = false }

[dev-dependencies]
num_cpus = "1.13"
